lib/host.ts
By resolving to wherever the typescript folder is installed into, we can
ensure that a reference to `lib.d.ts` will always be found.
=> Fixes #59 Resolves root directory for `lib.d.ts`

readme.md
Misplaced ']' in the example code.
=> Typo in the readme

lib/output.ts
From gulp-sourcemaps [documentation](https://github.com/floridoo/gulp-sourcemaps#plugin-developers-only-how-to-add-source-map-support-to-plugins):
> Important: Make sure the paths in the generated source map (file and sources)
are relative to file.base (e.g. use file.relative)
Fix the "file" property to meet the above requirement(before this commit only
"sources" are relative to file.base).
=> Make sourcemap 'file' property relative to file.base

lib/main.ts, lib/tsapi.ts
When I use the `gulp-typescript`, `ModuleResolution` option doesn't work at my TypeScript project(https://github.com/pocke/brainfuck-playground).
Because, `typescript.ModuleResolution` doesn't exist. However, `ModuleResolutionKind` exists instead of `ModuleResolution`.
I don't know how to build.
Because, can't find typescript module... 
error log
```
$ gulp
[13:04:21] Using gulpfile ~/ghq/github.com/ivogabe/gulp-typescript/gulpfile.js
[13:04:21] Starting 'clean'...
[13:04:21] Starting 'typecheck-1.4'...
[13:04:21] 'typecheck-1.4' errored after 419 μs
[13:04:21] Error: Cannot find module './typescript/1-4'
at Function.Module._resolveFilename (module.js:336:15)
at Function.require.resolve (module.js:388:19)
at findTSDefinition (/home/pocke/ghq/github.com/ivogabe/gulp-typescript/gulpfile.js:2 …
```
=> Enable to work ModuleResolution option.

readme.md
Added link to gulp-sourcemaps to avoid having to search for it.
=> Link to gulp-sourcemaps in readme

lib/filter.ts, release/filter.js
This fixes a bug where gulp-typescript fails to find a file listed in the `referencedFrom` filter list if that file lives in a parent directory of the gulpfile, e.g.:
```javascript
gulp.src(['files/**/*.ts', '../lib/**/*.ts'])
.pipe(ts.filter(project, { referencedFrom: ['../lib/test.ts'] }))
.pipe(gulp.dest('./dist'))
```
=> Fix bug when filtering reference in parent dir

gulpfile.js, lib/main.ts
LF/CRLF was wreaking havoc. Use gulp-eol to force all output to LF, and fix path separators in error output as needed.
=> Let tests pass on Windows

lib/main.ts
Addresses https://github.com/ivogabe/gulp-typescript/issues/296.
Removed the two cases for a bug in 1.4 that was causing issues with TS 1.8.
I can update to check for 1.4 to keep them in in as well, but just removed them because of their comments.
=> Don't provide default target or module type

gulpfile.js, lib/host.ts, lib/input.ts, lib/main.ts, lib/output.ts, lib/project.ts, lib/reporter.ts, lib/utils.ts, package.json, release/compiler.d.ts, release/filter.d.ts, release/host.d.ts, release/host.js, release/input.d.ts, release/input.js, release/main.d.ts, release/main.js, release/output.d.ts, release/output.js, release/project.d.ts, release/project.js, release/reporter.d.ts, release/reporter.js, release/tsapi.d.ts, release/tsconfig.d.ts, release/utils.d.ts, release/utils.js, release/vinyl-file.d.ts, release/vinyl-file.js, tsconfig.json
This PR bundles `.d.ts` information with the compiled JS and sets the `typings` property in `package.json` so dependent packages can use gulp-typescript typings in their `gulpfile.ts`*. In order to emit correct `.d.ts` files, `/// <reference/>`s to `tsd.d.ts` were removed. In fact, they are unnecessary when specifying the `tsd.d.ts` in the `tsconfig.json`, so it just cleans things up a bit. Additionally, all non-entry files were removed from `tsconfig.json` as Typescript will pick them up when you `import` them.
\* If you name your gulpfile `gulpfile.ts` and `npm install ts-node`, gulp will run your Typescript!
=> Include typing information in compiled release

lib/project.ts
This fixes an issue in which a `rootDir` specified in the gulp task was not being used to determine the value for `base` (`base` was always `undefined`).
`this.config.compilerOptions` only contains the options defined in the `tsconfig.json` file. Overrides defined when creating the `TsProject` instance must be accessed via `this.options`.
=> Use correct 'rootDir' setting in Project.src

lib/output.ts, release/output.js, test/baselines/sourceMaps/1.6/js/Main/MainFileTsx.js, test/baselines/sourceMaps/1.6/js/Main/MainFileTsx.js.map, test/baselines/sourceMaps/1.7/js/Main/MainFileTsx.js, test/baselines/sourceMaps/1.7/js/Main/MainFileTsx.js.map, test/baselines/sourceMaps/1.8/js/Main/MainFileTsx.js, test/baselines/sourceMaps/1.8/js/Main/MainFileTsx.js.map, test/baselines/sourceMaps/dev/js/Main/MainFileTsx.js, test/baselines/sourceMaps/dev/js/Main/MainFileTsx.js.map, test/sourceMaps/Main/MainFileTsx.tsx
Updated the code which modifies the sourceMap output file name to be relative to the source path so it uses the appropriate extension.
Instead of using a regex to replace the original file name's extension, it uses utils.split extension to take the first part of the original file name and the extension of the output file name, then gets the relative path using the source root.
I also added a .tsx file to the test cases and updated the baseline folder.
=> Changed sourcemap file path resolution to use correct extension

lib/output.ts
Due to the fact that `gulp-sourcemaps` library always creates new SourceMap using unix style paths (tHis can be clearly seen at the line 199 of [init.js](https://github.com/floridoo/gulp-sourcemaps/blob/6972337a0953e542768b29fb43c4c41eee535859/src/init.js)):
```
if (!sourceMap) {
// Make an empty source map
sourceMap = {
version: 3,
names: [],
mappings: '',
sources: [unixStylePath(file.relative)], // line 199, unix style path
sourcesContent: [fileContent]
};
}
```
`gulp-typescript` should also use unix style path when using `SourceMapGenerator.setSourceContent` method directly. Otherwise source maps for `ts` files in project subdirectories on Windows system are missing due to backslash/forwardslash missmatch in the `SourceMapGenerator` …
=> Fix missing source maps for ts files in subdirectories on Windows

package.json
This PR adds the `types` property to package.json.
This property is used to let Typescript 2 detect the type definitions automatically so consumers do not have to configure anything to use this library. The name of the property changed from `typings` to `types` with `typescript@2`. I left the previous name for compatibility.
Reference: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
=> Add `types` property to package.json

gulpfile.js
When parsing messages without filenames (such as "TypeScript error: error TS2318: Cannot find global type 'Array'.") on Windows, the return statement causes execution to break out of the error function before errors.push(err) occurs. Wrapping in a function ensures that `return` does not skip over pushing onto errors array.
=> Fixes Windows issue where 'return' occured early

readme.md
Users should not install gulp globally. Gulp-cli is the package for global installation, and gulp is the package for project level consumption.
=> Update global gulp references to gulp-cli

readme.md
Some people copy and paste code straight from github. Not me though, other people.
=> update readme to use outFile rather than deprecated out

gulpfile.js
The code prior to this patch was undercounting the number tests expected. If you added a `console.log` to check the value of `pending` in the `test-run` task, you'd see it go into the negative. The upshot was that Gulp would consider the tests done before they were actually done.
I discovered this while resuming work on #494. The test should have failed but I was not able to get a failure until I fixed the counting issue.
=> Fix the way tests are counted.

lib/main.ts
Fixes: 
- `compile()` overloads
- Overload order
- `createProject()` overloads
- Return type is now `Project` instead of `any`
- Overload order
I also locked `@types/node` version as later versions use newer TypeScript features that older versions of TypeScript can't handle.
=> Fix type definitions

.travis.yml, gulpfile.js, test/baselines/basic/2.3/errors.txt, test/baselines/basic/2.4/errors.txt, test/baselines/basic/dev/errors.txt, test/baselines/bom/2.3/errors.txt, test/baselines/bom/2.4/errors.txt, test/baselines/bom/dev/errors.txt, test/baselines/existingSourceMaps/2.3/errors.txt, test/baselines/existingSourceMaps/2.4/errors.txt, test/baselines/existingSourceMaps/dev/errors.txt, test/baselines/externalResolve/2.3/errors.txt, test/baselines/externalResolve/2.4/errors.txt, test/baselines/externalResolve/dev/errors.txt, test/baselines/out/2.3/errors.txt, test/baselines/out/2.4/errors.txt, test/baselines/out/dev/errors.txt, test/baselines/sourceMaps/2.3/errors.txt, test/baselines/sourceMaps/2.4/errors.txt, test/baselines/sourceMaps/dev/errors.txt, test/baselines/sourceMapsOutDir/2.3/errors.txt, test/baselines/sourceMapsOutDir/2.4/errors.txt, test/baselines/sourceMapsOutDir/dev/errors.txt, test/baselines/tsconfigExtends/2.3/errors.txt, test/baselines/tsconfigExtends/2.4/errors.txt, test/baselines/tsconfigExtends/dev/errors.txt, test/baselines/tsconfigOutFile/2.3/errors.txt, test/baselines/tsconfigOutFile/2.4/errors.txt, test/baselines/tsconfigOutFile/dev/errors.txt, test/noEmit/gulptask.js
Due to a mismatch in the argument and parameters of the `runTest`
function used to execute the test, failures were ignored.
This commit fixes the concerned functions and fixes this issue.
Closes ivogabe/gulp-typescript#544
=> Update test gulp tasks

lib/host.ts
TypeScript 3.1 requires that the `CompilerHost` for a program with project references must support `readDirectory`. This change adds `readDirectory` support via the fallback compiler host.
cc: @ivogabe
=> Fix minimal support for project references

lib/compiler.ts, test/baselines/emitDeclarationOnly/2.9/dts/a.d.ts, test/baselines/emitDeclarationOnly/2.9/errors.txt, test/baselines/emitDeclarationOnly/dev/dts/a.d.ts, test/baselines/emitDeclarationOnly/dev/errors.txt, test/emitDeclarationOnly/a.ts, test/emitDeclarationOnly/gulptask.js
Previously, if there was no JavaScript output from a file, the output would be skipped entirely. This meant that when emitDeclarationOnly was enabled, the declarations would not be written to the `dts` stream.
Fixes #607.
One note on the test case: I found it actually passed even before making the change because `gulp-diff` only checks the files that exist in the stream. For example, if the stream is empty, the test will pass, even if there are files in the `baseline` directory. I did verify that, after my change, if the output differs, the test will fail.
=> Output declarations with emitDeclarationOnly

lib/reporter.ts, release/reporter.js
Tweak the `fullReporter` slightly to display the correct line and column highlighting.
No tests included; I don't see an easy way to provide a test for a reporter given the current approach, but let me know if I'm missing something.
Using this example build, here are before and after screenshots of the output...
```js
// gulpfile.js
module.exports.default = () => {
const ts = typescript.createProject('tsconfig.json', typescript.reporter.fullReporter());
return gulp.src('src/ts/example.ts')
.pipe(ts(typescript.reporter.fullReporter())).js
.pipe(gulp.dest('dist'));
};
```
```js
// src/ts/example.ts
export function example() {
console.log(Math.squeak());
}
```
=> fix(fullReporter): Fix off-by-one display issue

gulpfile.js
I got a mail that the tests failed on Windows because of the use of execFile. `execFile` executes a command without opening a shell, whereas `exec` will first open a shell and then execute a command. I think that a shell is needed for Windows, as it did work on Mac and Linux.
@lddubeau Do you agree with this change?
(The commit name should be the other way around..)
=> Replace execFile with exec to fix tests on Windows
