package.json

Adds the names and email addresses for developers that have contributed
to the project.

Inserts a `contributors` field to `package.json`

---

lib/project.ts
release/project.js

FIX filename value.

---

lib/compiler.ts
lib/input.ts
release/compiler.js
release/input.js

Common base path

---

lib/compiler.ts
lib/input.ts
lib/output.ts
release/compiler.js
release/input.js
release/output.js

Calculate common source directory for files outside the common base path.

---

readme.md

- Basis -> Basic
- minimalist -> minimal (minimalist is a person)
- script -> scripts (to make task names match)

Minor readme.md copy edits.

---

readme.md

the property was listed twice in this section.

remove duplicate option definition in readme

---

lib/compiler.ts
test/baselines/sourceMaps/1.4/errors.txt
test/baselines/sourceMaps/1.4/js/Main/MainFile.js
test/baselines/sourceMaps/1.4/js/Main/MainFile.js.map
test/baselines/sourceMaps/1.5/errors.txt
test/baselines/sourceMaps/1.5/js/Main/MainFile.js
test/baselines/sourceMaps/1.5/js/Main/MainFile.js.map
test/baselines/sourceMaps/1.6/errors.txt
test/baselines/sourceMaps/1.6/js/Main/MainFile.js
test/baselines/sourceMaps/1.6/js/Main/MainFile.js.map
test/baselines/sourceMaps/1.7/errors.txt
test/baselines/sourceMaps/1.7/js/Main/MainFile.js
test/baselines/sourceMaps/1.7/js/Main/MainFile.js.map
test/baselines/sourceMaps/1.8/errors.txt
test/baselines/sourceMaps/1.8/js/Main/MainFile.js
test/baselines/sourceMaps/1.8/js/Main/MainFile.js.map
test/baselines/sourceMaps/dev/errors.txt
test/baselines/sourceMaps/dev/js/Main/MainFile.js
test/baselines/sourceMaps/dev/js/Main/MainFile.js.map
test/sourceMaps/Main/MainFile.ts
test/sourceMaps/Main/tsconfig.json
test/sourceMaps/Outer/Foo.ts
test/sourceMaps/gulptask.js

fixes #255 - don't change filename/path casing when adjusting source map sources

Sourcemap casing

---

lib/input.ts

The for-in loop was iterating over an array of strings, which results in the numeric indices of the array instead of the filenames.
Changed to the default for loop.
[http://stackoverflow.com/a/7480175](http://stackoverflow.com/a/7480175)

Fixed the for in loop.

---

readme.md

Replacing tabs with spaces in README.md

---

readme.md

Extend the "build gulp-typescript" instructions

---

lib/project.ts
lib/types.ts
release/main.js
release/project.js
release/types.d.ts

See issue: https://github.com/ivogabe/gulp-typescript/issues/320

 Added support for TypeScript 2.0 'include' config option (#320)

---

lib/types.ts
package.json

- reflect [version update](https://github.com/Microsoft/TypeScript/blob/master/package.json#L5) in TypeScript nightly builds
- update `RawSourceMap` to [match changes](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/79f48dd449b0542cece6964b0cf761ee5316c435#diff-acd1cc7ef767fdde0d9d828f3deb3fca) on DefinitelyTyped

update version of TypeScript peer dependency

---

lib/output.ts
test/baselines/existingSourceMaps/2.0/errors.txt
test/baselines/existingSourceMaps/2.0/js/all.js
test/baselines/existingSourceMaps/2.0/js/all.js.map
test/baselines/existingSourceMaps/dev/errors.txt
test/baselines/existingSourceMaps/dev/js/all.js
test/baselines/existingSourceMaps/dev/js/all.js.map
test/existingSourceMaps/apple.ts
test/existingSourceMaps/banana.ts
test/existingSourceMaps/gulptask.js

Pull request for my "Optional/Second Solution" regarding source maps not being correctly mapped for preprocessed files. I have also included a test around my scenario!

fixed sourcemap sources being lost for files with existing mappings #460

---

package.json

update peer dependencies to support TS 2.3

---

lib/compiler.ts

Fixes performance issues as described in #495.

Fix performance issues

---

package.json

We will also need a new version pushed to npm with the change.
Related to https://github.com/Microsoft/TypeScript/pull/16049

update peer dependencies to support TS 2.4

---

readme.md

Just fixing a simple spelling error I found in the documentation. :)

Fixing spelling error

---

package.json

[They will start version 2.8 in few days.](https://github.com/Microsoft/TypeScript/pull/21319)

Accept typescript >=2.8.0-dev

---

package.json

[Just created](https://github.com/Microsoft/TypeScript/pull/22803).

Accept typescript >=2.9.0-dev

---

lib/reporter.ts
package-lock.json
package.json

Fixed ansi-colors dependency
